name: CI Pipeline

on:
  pull_request:
    branches: [main]
    

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.7
        
      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with: 
          java-version: '17'
          distribution: 'adopt'

      - name: Lint
        run: ./gradlew lint

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew build

      - name: Upload a build artifect
        uses: actions/upload-artifact@v4.3.4
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk
        
              
    
  
